### ISSUE TITLE
Subpalette not shown

### ISSUE THREAD

**Issue by rorych** [heimrichhannot/contao-multifileupload-bundle#5] opened 2019-01-30 16:36 UTC
System: 4.4.28
Plugin: 1.1.3

In the Formgenerator, if the "Labelless" Formfieldtyp is choosen, the Subpalette basically is empty.
There are no options shown.

Not shure if the dca for that is missing.

**Comment by fatcrobat** [comment] 2019-02-14 10:54
Duplicate of #1

**Closed by fatcrobat** 2019-02-14 10:54 UTC
Labels: duplicate
